New upstream version 1.8.0

diff --git a/tests/shtest b/tests/shtest
--- a/tests/shtest
+++ b/tests/shtest
@@ -14,6 +14,12 @@ JQ="$JQ -b"
 
 PATH=$JQBASEDIR:$PATH $JQBASEDIR/tests/jq-f-test.sh > /dev/null
 
+SHELL=/bin/sh
+export SHELL
+
+unset JQ_COLORS
+unset NO_COLOR
+
 if [ -f "$JQBASEDIR/.libs/libinject_errors.so" ]; then
   # Do some simple error injection tests to check that we're handling
   # I/O errors correctly.
@@ -34,77 +40,17 @@ $VALGRIND $Q $JQ -Rse '. == "a\u0000b\nc\u0000d\ne"' $d/input
 $VALGRIND $Q $JQ -Rne '[inputs] == ["a\u0000b", "c\u0000d", "e"]' $d/input
 
 ## Test constant folding
-
-## XXX If we add a builtin to list the program's disassembly then we can
-## move all of these into tests/all.test
-
-# String constant folding (addition only)
 nref=$($VALGRIND $Q $JQ -n --debug-dump-disasm '"foo"' | wc -l)
-n=$($VALGRIND $Q $JQ -n --debug-dump-disasm '"foo" + "bar"' | wc -l)
-if [ $n -ne $nref ]; then
-  echo "Constant expression folding for strings didn't work"
-  exit 1
-fi
-
-# Numeric constant folding (binary operators)
-n=$($VALGRIND $Q $JQ -n --debug-dump-disasm '1+1' | wc -l)
-if [ $n -ne $nref ]; then
-  echo "Constant expression folding for numbers didn't work"
-  exit 1
-fi
-n=$($VALGRIND $Q $JQ -n --debug-dump-disasm '1-1' | wc -l)
-if [ $n -ne $nref ]; then
-  echo "Constant expression folding for numbers didn't work"
-  exit 1
-fi
-n=$($VALGRIND $Q $JQ -n --debug-dump-disasm '2*3' | wc -l)
-if [ $n -ne $nref ]; then
-  echo "Constant expression folding for numbers didn't work"
-  exit 1
-fi
-n=$($VALGRIND $Q $JQ -n --debug-dump-disasm '9/3' | wc -l)
-if [ $n -ne $nref ]; then
-  echo "Constant expression folding for numbers didn't work"
-  exit 1
-fi
-n=$($VALGRIND $Q $JQ -n --debug-dump-disasm '9%3' | wc -l)
-if [ $n -ne $nref ]; then
-  echo "Constant expression folding for numbers didn't work"
-  exit 1
-fi
-n=$($VALGRIND $Q $JQ -n --debug-dump-disasm '9==3' | wc -l)
-if [ $n -ne $nref ]; then
-  echo "Constant expression folding for numbers didn't work"
-  exit 1
-fi
-n=$($VALGRIND $Q $JQ -n --debug-dump-disasm '9!=3' | wc -l)
-if [ $n -ne $nref ]; then
-  echo "Constant expression folding for numbers didn't work"
-  exit 1
-fi
-n=$($VALGRIND $Q $JQ -n --debug-dump-disasm '9<3' | wc -l)
-if [ $n -ne $nref ]; then
-  echo "Constant expression folding for numbers didn't work"
-  exit 1
-fi
-n=$($VALGRIND $Q $JQ -n --debug-dump-disasm '9>3' | wc -l)
-if [ $n -ne $nref ]; then
-  echo "Constant expression folding for numbers didn't work"
-  exit 1
-fi
-n=$($VALGRIND $Q $JQ -n --debug-dump-disasm '9<=3' | wc -l)
-if [ $n -ne $nref ]; then
-  echo "Constant expression folding for numbers didn't work"
-  exit 1
-fi
-n=$($VALGRIND $Q $JQ -n --debug-dump-disasm '9>=3' | wc -l)
-if [ $n -ne $nref ]; then
-  echo "Constant expression folding for numbers didn't work"
-  exit 1
-fi
+for exp in '1+1' '1-1' '2*3' '9/3' '9%3' '9==3' '9!=3' \
+  '9<3' '9>3' '9<=3' '9>=3' '1+2*3-4/5%6' '"foo" + "bar"'; do
+  n=$($VALGRIND $Q $JQ -n --debug-dump-disasm "$exp" | wc -l)
+  if [ $n -ne $nref ]; then
+    echo "Constant expression folding didn't work: $exp"
+    exit 1
+  fi
+done
 
 ## Test JSON sequence support
-
 cat > $d/expected <<EOF
 jq: ignoring parse error: Truncated value at line 2, column 5
 jq: ignoring parse error: Truncated value at line 2, column 25
@@ -151,6 +97,20 @@ if printf '1\n' | $JQ -cen --seq '[inputs] == []' >/dev/null 2> $d/out; then
 fi
 cmp $d/out $d/expected
 
+# Test control characters for #2909
+cat > $d/expected <<EOF
+jq: parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 1, column 3
+EOF
+for i in 1 2 30 31; do
+  if printf "\"$(printf '\\%03o' $i)\"" | $JQ '.' > $d/out 2>&1; then
+    printf 'Error expected but jq exited successfully\n' 1>&2
+    exit 2
+  fi
+  cmp $d/out $d/expected
+done
+printf '" ~\\u007f"\n' > $d/expected
+printf "\"$(printf '\\%03o' 32 126 127)\"" | $JQ '.' > $d/out 2>&1
+cmp $d/out $d/expected
 
 ## Test --exit-status
 data='{"i": 1}\n{"i": 2}\n{"i": 3}\n'
@@ -195,12 +155,19 @@ cmp $d/out $d/expected
 printf "[1,2][3,4]\n" | $JQ -cs add > $d/out 2>&1
 cmp $d/out $d/expected
 
+# Regression test for #3273
+echo "[[[0],1],[[0]],[[0],2],[[0]]]" > $d/expected
+printf "[1][2]" | $JQ -c -s --stream . > $d/out 2>&1
+cmp $d/out $d/expected
+printf "[1][2]\n" | $JQ -c -s --stream . > $d/out 2>&1
+cmp $d/out $d/expected
+
 # Regression test for --raw-output0
 printf "a\0b\0" > $d/expected
-printf '["a", "b"]' | $VALGRIND $Q $JQ --raw-output0 .[] > $d/out
+printf '["a", "b"]' | $VALGRIND $Q $JQ --raw-output0 '.[]' > $d/out
 cmp $d/out $d/expected
 printf "a\0" > $d/expected
-if printf '["a", "c\\u0000d", "b"]' | $VALGRIND $Q $JQ --raw-output0 .[] > $d/out; then
+if printf '["a", "c\\u0000d", "b"]' | $VALGRIND $Q $JQ --raw-output0 '.[]' > $d/out; then
   echo "Should exit error on string containing NUL with --raw-output0" 1>&2
   exit 1
 elif [ $? -ne 5 ]; then
@@ -208,6 +175,34 @@ elif [ $? -ne 5 ]; then
   exit 1
 else
   cmp $d/out $d/expected
+fi
+
+# Regression tests for #3194
+echo 42 > $d/expected
+$JQ -nn 42 > $d/out 2>&1
+cmp $d/out $d/expected
+
+$JQ -nL. 42 > $d/out 2>&1
+cmp $d/out $d/expected
+$JQ -nL . 42 > $d/out 2>&1
+cmp $d/out $d/expected
+
+$JQ -h > $d/expected 2>&1
+$JQ -hV > $d/out 2>&1
+cmp $d/out $d/expected
+$JQ -h -V > $d/out 2>&1
+cmp $d/out $d/expected
+
+$JQ -V > $d/expected 2>&1
+$JQ -Vh > $d/out 2>&1
+cmp $d/out $d/expected
+$JQ -V -h > $d/out 2>&1
+cmp $d/out $d/expected
+
+# CRLF line break support #1219
+if ! x=$($JQ -n "$(printf '1\r\n+\r\n2')") || [ "$x" != '3' ]; then
+  echo 'CRLF line break support failed?' 1>&2
+  exit 1
 fi
 
 ## Test streaming parser
@@ -359,6 +354,17 @@ if [ "$(HOME="$mods/home1" $VALGRIND $Q $JQ -nr fg)" != foobar ]; then
     exit 1
 fi
 
+if $msys || $mingw; then
+    HOME_BAK=$HOME
+    unset HOME
+    if [ "$(USERPROFILE="$mods/home1" $VALGRIND $Q $JQ -nr foo)" != baz ]; then
+        echo "Bug #3104 regressed (sourcing %USERPROFILE%/.jq on Windows)" 1>&2
+        exit 1
+    fi
+    export HOME=$HOME_BAK
+    unset HOME_BAK
+fi
+
 if [ $(HOME="$mods/home1" $VALGRIND $Q $JQ --debug-dump-disasm -n fg | grep '^[a-z]' | wc -l) -ne 3 ]; then
     echo "Binding too many defs into program" 1>&2
     exit 1
@@ -423,7 +429,6 @@ if [ "$($VALGRIND $Q $JQ -n '{"a":"xyz"} | halt_error(1)' 2>&1)" != '{"a":"xyz"}
 fi
 
 # Check $JQ_COLORS
-unset JQ_COLORS
 
 ## Default colors, null input
 $JQ -Ccn . > $d/color
@@ -435,79 +440,180 @@ JQ_COLORS='4;31' $JQ -Ccn . > $d/color
 printf '\033[4;31mnull\033[0m\n' > $d/expect
 cmp $d/color $d/expect
 
+## Set implicit empty color, null input
+$JQ -Ccn . > $d/color
+printf '\033[0;90mnull\033[0m\n' > $d/expect
+cmp $d/color $d/expect
+
+## Set explicit empty color, null input
+JQ_COLORS=':' $JQ -Ccn . > $d/color
+printf '\033[mnull\033[0m\n' > $d/expect
+cmp $d/color $d/expect
+
+## Extra colors, null input
+JQ_COLORS='::::::::' $JQ -Ccn . > $d/color
+printf '\033[mnull\033[0m\n' > $d/expect
+cmp $d/color $d/expect
+
 ## Default colors, complex input
-$JQ -Ccn '[{"a":true,"b":false},123,null]' > $d/color
+$JQ -Ccn '[{"a":true,"b":false},"abc",123,null]' > $d/color
 {
-  printf '\033[1;39m[\033[1;39m{'
-  printf '\033[0m\033[1;34m"a"\033['
-  printf '0m\033[1;39m:\033[0m\033['
-  printf '0;39mtrue\033[0m\033[1'
-  printf ';39m,\033[0m\033[1;34m'
-  printf '"b"\033[0m\033[1;39m:\033'
-  printf '[0m\033[0;39mfalse\033'
-  printf '[0m\033[1;39m\033[1;39'
-  printf 'm}\033[0m\033[1;39m,\033['
-  printf '0;39m123\033[0m\033[1;'
-  printf '39m,\033[0;90mnull\033'
-  printf '[0m\033[1;39m\033[1;39'
-  printf 'm]\033[0m\n'
+  printf '\033[1;39m[\033[0m'
+  printf '\033[1;39m{\033[0m'
+  printf '\033[1;34m"a"\033[0m'
+  printf '\033[1;39m:\033[0m'
+  printf '\033[0;39mtrue\033[0m'
+  printf '\033[1;39m,\033[0m'
+  printf '\033[1;34m"b"\033[0m'
+  printf '\033[1;39m:\033[0m'
+  printf '\033[0;39mfalse\033[0m'
+  printf '\033[1;39m}\033[0m'
+  printf '\033[1;39m,\033[0m'
+  printf '\033[0;32m"abc"\033[0m'
+  printf '\033[1;39m,\033[0m'
+  printf '\033[0;39m123\033[0m'
+  printf '\033[1;39m,\033[0m'
+  printf '\033[0;90mnull\033[0m'
+  printf '\033[1;39m]\033[0m\n'
 } > $d/expect
 cmp $d/color $d/expect
 
 ## Set non-default colors, complex input
 JQ_COLORS='0;30:0;31:0;32:0;33:0;34:1;35:1;36:1;37' \
-  $JQ -Ccn '[{"a":true,"b":false},123,null]' > $d/color
+  $JQ -Ccn '[{"a":true,"b":false},"abc",123,null]' > $d/color
 {
-  printf '\033[1;35m[\033[1;36m{'
-  printf '\033[0m\033[1;37m"a"\033['
-  printf '0m\033[1;36m:\033[0m\033['
-  printf '0;32mtrue\033[0m\033[1'
-  printf ';36m,\033[0m\033[1;37m'
-  printf '"b"\033[0m\033[1;36m:\033'
-  printf '[0m\033[0;31mfalse\033'
-  printf '[0m\033[1;36m\033[1;36'
-  printf 'm}\033[0m\033[1;35m,\033['
-  printf '0;33m123\033[0m\033[1;'
-  printf '35m,\033[0;30mnull\033'
-  printf '[0m\033[1;35m\033[1;35'
-  printf 'm]\033[0m\n'
+  printf '\033[1;35m[\033[0m'
+  printf '\033[1;36m{\033[0m'
+  printf '\033[1;37m"a"\033[0m'
+  printf '\033[1;36m:\033[0m'
+  printf '\033[0;32mtrue\033[0m'
+  printf '\033[1;36m,\033[0m'
+  printf '\033[1;37m"b"\033[0m'
+  printf '\033[1;36m:\033[0m'
+  printf '\033[0;31mfalse\033[0m'
+  printf '\033[1;36m}\033[0m'
+  printf '\033[1;35m,\033[0m'
+  printf '\033[0;34m"abc"\033[0m'
+  printf '\033[1;35m,\033[0m'
+  printf '\033[0;33m123\033[0m'
+  printf '\033[1;35m,\033[0m'
+  printf '\033[0;30mnull\033[0m'
+  printf '\033[1;35m]\033[0m\n'
 } > $d/expect
 cmp $d/color $d/expect
 
-# Check garbage in JQ_COLORS.  We write each color sequence into a 16
-# char buffer that needs to hold ESC [ <color> m NUL, so each color
-# sequence can be no more than 12 chars (bytes).  These emit a warning
-# on stderr.
-set -vx
+## Set non-default colors only for literals, complex input
+JQ_COLORS='0;37:0;31:0;35:0;34:0;36' \
+  $JQ -Ccn '[{"a":true,"b":false},"abc",123,null]' > $d/color
+{
+  printf '\033[1;39m[\033[0m'
+  printf '\033[1;39m{\033[0m'
+  printf '\033[1;34m"a"\033[0m'
+  printf '\033[1;39m:\033[0m'
+  printf '\033[0;35mtrue\033[0m'
+  printf '\033[1;39m,\033[0m'
+  printf '\033[1;34m"b"\033[0m'
+  printf '\033[1;39m:\033[0m'
+  printf '\033[0;31mfalse\033[0m'
+  printf '\033[1;39m}\033[0m'
+  printf '\033[1;39m,\033[0m'
+  printf '\033[0;36m"abc"\033[0m'
+  printf '\033[1;39m,\033[0m'
+  printf '\033[0;34m123\033[0m'
+  printf '\033[1;39m,\033[0m'
+  printf '\033[0;37mnull\033[0m'
+  printf '\033[1;39m]\033[0m\n'
+} > $d/expect
+cmp $d/color $d/expect
+
+## Default colors, complex input, indented
+$JQ -Cn '[{"a":true,"b":false},"abc",123,null]' > $d/color
+{
+  printf '\033[1;39m[\033[0m\n'
+  printf '  \033[1;39m{\033[0m\n'
+  printf '    \033[1;34m"a"\033[0m'
+  printf '\033[1;39m:\033[0m '
+  printf '\033[0;39mtrue\033[0m'
+  printf '\033[1;39m,\033[0m\n'
+  printf '    \033[1;34m"b"\033[0m'
+  printf '\033[1;39m:\033[0m '
+  printf '\033[0;39mfalse\033[0m\n'
+  printf '  \033[1;39m}\033[0m'
+  printf '\033[1;39m,\033[0m\n'
+  printf '  \033[0;32m"abc"\033[0m'
+  printf '\033[1;39m,\033[0m\n'
+  printf '  \033[0;39m123\033[0m'
+  printf '\033[1;39m,\033[0m\n'
+  printf '  \033[0;90mnull\033[0m\n'
+  printf '\033[1;39m]\033[0m\n'
+} > $d/expect
+cmp $d/color $d/expect
+
+## Set non-default colors, complex input, indented
+JQ_COLORS='0;30:0;31:0;32:0;33:0;34:1;35:1;36:1;37' \
+  $JQ -Cn '[{"a":true,"b":false},"abc",123,null]' > $d/color
+{
+  printf '\033[1;35m[\033[0m\n'
+  printf '  \033[1;36m{\033[0m\n'
+  printf '    \033[1;37m"a"\033[0m'
+  printf '\033[1;36m:\033[0m '
+  printf '\033[0;32mtrue\033[0m'
+  printf '\033[1;36m,\033[0m\n'
+  printf '    \033[1;37m"b"\033[0m'
+  printf '\033[1;36m:\033[0m '
+  printf '\033[0;31mfalse\033[0m\n'
+  printf '  \033[1;36m}\033[0m'
+  printf '\033[1;35m,\033[0m\n'
+  printf '  \033[0;34m"abc"\033[0m'
+  printf '\033[1;35m,\033[0m\n'
+  printf '  \033[0;33m123\033[0m'
+  printf '\033[1;35m,\033[0m\n'
+  printf '  \033[0;30mnull\033[0m\n'
+  printf '\033[1;35m]\033[0m\n'
+} > $d/expect
+cmp $d/color $d/expect
+
+## Set truecolor, complex input, indented
+JQ_COLORS=$(printf '38;2;%s:' \
+  '255;173;173' '255;214;165' '253;255;182' '202;255;191' \
+  '155;246;255' '160;196;255' '189;178;255' '255;198;255') \
+  $JQ -Cn '[{"a":true,"b":false},"abc",123,null]' > $d/color
+{
+  printf '\033[38;2;160;196;255m[\033[0m\n'
+  printf '  \033[38;2;189;178;255m{\033[0m\n'
+  printf '    \033[38;2;255;198;255m"a"\033[0m'
+  printf '\033[38;2;189;178;255m:\033[0m '
+  printf '\033[38;2;253;255;182mtrue\033[0m'
+  printf '\033[38;2;189;178;255m,\033[0m\n'
+  printf '    \033[38;2;255;198;255m"b"\033[0m'
+  printf '\033[38;2;189;178;255m:\033[0m '
+  printf '\033[38;2;255;214;165mfalse\033[0m\n'
+  printf '  \033[38;2;189;178;255m}\033[0m'
+  printf '\033[38;2;160;196;255m,\033[0m\n'
+  printf '  \033[38;2;155;246;255m"abc"\033[0m'
+  printf '\033[38;2;160;196;255m,\033[0m\n'
+  printf '  \033[38;2;202;255;191m123\033[0m'
+  printf '\033[38;2;160;196;255m,\033[0m\n'
+  printf '  \033[38;2;255;173;173mnull\033[0m\n'
+  printf '\033[38;2;160;196;255m]\033[0m\n'
+} > $d/expect
+cmp $d/color $d/expect
+
+# Check invalid JQ_COLORS
 echo 'Failed to set $JQ_COLORS' > $d/expect_warning
-$JQ -Ccn '[{"a":true,"b":false},123,null]' > $d/expect
-JQ_COLORS='garbage;30:*;31:,;3^:0;$%:0;34:1;35:1;36' \
-  $JQ -Ccn '[{"a":true,"b":false},123,null]' > $d/color 2>$d/warning
-cmp $d/color $d/expect
-cmp $d/warning $d/expect_warning
-JQ_COLORS='1234567890123456789;30:0;31:0;32:0;33:0;34:1;35:1;36' \
-  $JQ -Ccn '[{"a":true,"b":false},123,null]' > $d/color 2>$d/warning
-cmp $d/color $d/expect
-cmp $d/warning $d/expect_warning
-JQ_COLORS='1;31234567890123456789:0;31:0;32:0;33:0;34:1;35:1;36' \
-  $JQ -Ccn '[{"a":true,"b":false},123,null]' > $d/color 2>$d/warning
-cmp $d/color $d/expect
-cmp $d/warning $d/expect_warning
-JQ_COLORS='1234567890123456;1234567890123456:1234567890123456;1234567890123456:1234567890123456;1234567890123456:1234567890123456;1234567890123456:1234567890123456;1234567890123456:1234567890123456;1234567890123456:1234567890123456;1234567890123456' \
-  $JQ -Ccn '[{"a":true,"b":false},123,null]' > $d/color 2>$d/warning
-cmp $d/color $d/expect
-cmp $d/warning $d/expect_warning
-JQ_COLORS="0123456789123:0123456789123:0123456789123:0123456789123:0123456789123:0123456789123:0123456789123:0123456789123:" \
-  $JQ -Ccn '[{"a":true,"b":false},123,null]' > $d/color 2>$d/warning
-cmp $d/color $d/expect
-cmp $d/warning $d/expect_warning
+$JQ -Ccn '[{"a":true,"b":false},"abc",123,null]' > $d/expect
+for colors in '/' '[30' '30m' '30:31m:32' '30:*:31' 'invalid'; do
+  JQ_COLORS=$colors \
+    $JQ -Ccn '[{"a":true,"b":false},"abc",123,null]' > $d/color 2>$d/warning
+  cmp $d/color $d/expect
+  cmp $d/warning $d/expect_warning
+done
 
 # Check $NO_COLOR
 test_no_color=true
 $msys  && test_no_color=false
 $mingw && test_no_color=false
 if $test_no_color && command -v script >/dev/null 2>&1; then
-  unset NO_COLOR
   if script -qc echo /dev/null >/dev/null 2>&1; then
     faketty() { script -qec "$*" /dev/null; }
   else # macOS
@@ -520,17 +626,17 @@ if $test_no_color && command -v script >/dev/null 2>&1; then
   od -tc $d/expect
   od -tc $d/color
   cmp $d/color $d/expect
-  NO_COLOR= faketty $JQ_NO_B -n . > $d/color
+  faketty env NO_COLOR= $JQ_NO_B -n . > $d/color
   printf '\033[0;90mnull\033[0m\r\n' > $d/expect
   od -tc $d/expect
   od -tc $d/color
   cmp $d/color $d/expect
-  NO_COLOR=1 faketty $JQ_NO_B -n . > $d/color
+  faketty env NO_COLOR=1 $JQ_NO_B -n . > $d/color
   printf 'null\r\n' > $d/expect
   od -tc $d/expect
   od -tc $d/color
   cmp $d/color $d/expect
-  NO_COLOR=1 faketty $JQ_NO_B -Cn . > $d/color
+  faketty env NO_COLOR=1 $JQ_NO_B -Cn . > $d/color
   printf '\033[0;90mnull\033[0m\r\n' > $d/expect
   od -tc $d/expect
   od -tc $d/color
@@ -582,6 +688,29 @@ EOF
   fi
 fi
 
+# Test syntax error messages of multiline filter (we can't test in jq.test)
+if $VALGRIND $Q $JQ -n '[
+  try if .
+         then 1
+         else 2
+  catch ]' > $d/out 2>&1; then
+  echo 'syntax error not detected'
+  exit 1
+fi
+cat > $d/expected <<EOF
+jq: error: syntax error, unexpected catch, expecting end or '|' or ',' at <top-level>, line 5, column 3:
+      catch ]
+      ^^^^^
+jq: error: Possibly unterminated 'if' statement at <top-level>, line 2, column 7:
+      try if .
+          ^^^^
+jq: error: Possibly unterminated 'try' statement at <top-level>, line 2, column 3:
+      try if .
+      ^^^^^^^^
+jq: 3 compile errors
+EOF
+diff $d/out $d/expected
+
 # Comments!
 if ! x=$($JQ -n '123 # comment') || [ "$x" != 123 ]; then
   echo 'comment did not work'
@@ -594,10 +723,29 @@ if ! x=$($JQ -n "1 # foo$cr + 2") || [ "$x" != 1 ]; then
   exit 1
 fi
 
-# CVE-2023-50268: No stack overflow comparing a nan with a large payload
-$VALGRIND $Q $JQ '1 != .' <<\EOF >/dev/null
-Nan4000
-EOF
+if ! x=$($JQ -cn '[
+  1,
+  # foo \
+  2,
+  # bar \\
+  3,
+  4, # baz \\\
+  5, \
+  6,
+  7
+  # comment \
+    comment \
+    comment
+]') || [ "$x" != '[1,3,4,7]' ]; then
+  echo 'multiline comment was not handled correctly'
+  exit 1
+fi
+
+if ! x=$($JQ -cn "$(printf '[\r\n1,# comment\r\n2,# comment\\\r\ncomment\r\n3\r\n]')") \
+  || [ "$x" != '[1,2,3]' ]; then
+  echo 'multiline comment with CRLF line breaks was not handled correctly'
+  exit 1
+fi
 
 # Allow passing the inline jq script before -- #2919
 if ! r=$($JQ --args -rn -- '$ARGS.positional[0]' bar) || [ "$r" != bar ]; then
@@ -613,5 +761,71 @@ fi
 $VALGRIND $Q $JQ . <<\NUM
 -10E-1000000001
 NUM
+
+# test for --indent and --compact-output -- #1465
+printf '[1,2]\n' > $d/expected
+$JQ --compact-output -n "[1,2]" > $d/out
+cmp $d/out $d/expected
+
+printf '[\n1,\n2\n]\n' > $d/expected
+$JQ --indent 0 -n "[1,2]" > $d/out
+cmp $d/out $d/expected
+
+printf '[\n 1,\n 2\n]\n' > $d/expected
+$JQ --indent 1 -n "[1,2]" > $d/out
+cmp $d/out $d/expected
+
+printf '[\n     1,\n     2\n]\n' > $d/expected
+$JQ --indent 5 -n "[1,2]" > $d/out
+cmp $d/out $d/expected
+
+printf '[\n{\n"a": 1\n}\n]\n' > $d/expected
+$JQ --indent 0 -n "[{a:1}]" > $d/out
+cmp $d/out $d/expected
+
+printf '[\n {\n  "a": 1\n }\n]\n' > $d/expected
+$JQ --indent 1 -n "[{a:1}]" > $d/out
+cmp $d/out $d/expected
+
+printf '[\n      {\n            "a": 1\n      }\n]\n' > $d/expected
+$JQ --indent 6 -n "[{a:1}]" > $d/out
+cmp $d/out $d/expected
+
+if ! $msys && ! $mingw; then
+  # Test handling of timezones -- #2429, #2475
+  if ! r=$(TZ=Asia/Tokyo $JQ -rn '1731627341 | strflocaltime("%F %T %z %Z")') \
+    || [ "$r" != "2024-11-15 08:35:41 +0900 JST" ]; then
+    echo "Incorrectly formatted local time"
+    exit 1
+  fi
+
+  if ! r=$(TZ=Europe/Paris $JQ -rn '1731627341 | strflocaltime("%F %T %z %Z")') \
+    || [ "$r" != "2024-11-15 00:35:41 +0100 CET" ]; then
+    echo "Incorrectly formatted local time"
+    exit 1
+  fi
+
+  # Test when DST is in effect: #1912
+  if ! r=$(TZ=Europe/Paris $JQ -rn '1750500000 | strflocaltime("%F %T %z %Z")') \
+    || [ "$r" != "2025-06-21 12:00:00 +0200 CEST" ]; then
+    echo "Incorrectly formatted local time"
+    exit 1
+  fi
+
+  if ! r=$(TZ=Europe/Paris $JQ -rn '1731627341 | strftime("%F %T %z %Z")') \
+    || ( [ "$r" != "2024-11-14 23:35:41 +0000 UTC" ] \
+      && [ "$r" != "2024-11-14 23:35:41 +0000 GMT" ] ); then
+    echo "Incorrectly formatted universal time"
+    exit 1
+  fi
+
+  if ! r=$(TZ=Etc/GMT+7 $JQ -nc '1731627341 | .,. | [strftime("%FT%T"),strflocaltime("%FT%T%z")]'
+) \
+    || [ "$r" != '["2024-11-14T23:35:41","2024-11-14T16:35:41-0700"]
+["2024-11-14T23:35:41","2024-11-14T16:35:41-0700"]' ]; then
+    echo "strftime or strftimelocal are not pure functions"
+    exit 1
+  fi
+fi
 
 exit 0
