New upstream version 1.7.1

diff --git a/tests/shtest b/tests/shtest
--- a/tests/shtest
+++ b/tests/shtest
@@ -244,7 +244,7 @@ if which seq > /dev/null 2>&1; then
         if [ -n "$VALGRIND" ]; then
             grep '^==[0-9][0-9]*== ERROR SUMMARY: 0 errors' $d/err > /dev/null
         else
-            tail -1 $d/err | egrep -i 'assert|abort|core' && false
+            tail -n1 -- "$d/err" | grep -Ei 'assert|abort|core' && false
         fi
 
         dd "if=tests/torture/input0.json" bs=$i count=1 2>/dev/null |
@@ -252,7 +252,7 @@ if which seq > /dev/null 2>&1; then
         if [ -n "$VALGRIND" ]; then
             grep '^==[0-9][0-9]*== ERROR SUMMARY: 0 errors' $d/err > /dev/null
         else
-            tail -1 $d/err | egrep -i 'assert|abort|core' && false
+            tail -n1 -- "$d/err" | grep -Ei 'assert|abort|core' && false
         fi
 
         diff $d/out0 $d/out1
@@ -438,18 +438,18 @@ cmp $d/color $d/expect
 ## Default colors, complex input
 $JQ -Ccn '[{"a":true,"b":false},123,null]' > $d/color
 {
-  printf '\033[1;37m[\033[1;37m{'
+  printf '\033[1;39m[\033[1;39m{'
   printf '\033[0m\033[1;34m"a"\033['
-  printf '0m\033[1;37m:\033[0m\033['
-  printf '0;37mtrue\033[0m\033[1'
-  printf ';37m,\033[0m\033[1;34m'
-  printf '"b"\033[0m\033[1;37m:\033'
-  printf '[0m\033[0;37mfalse\033'
-  printf '[0m\033[1;37m\033[1;37'
-  printf 'm}\033[0m\033[1;37m,\033['
-  printf '0;37m123\033[0m\033[1;'
-  printf '37m,\033[0;90mnull\033'
-  printf '[0m\033[1;37m\033[1;37'
+  printf '0m\033[1;39m:\033[0m\033['
+  printf '0;39mtrue\033[0m\033[1'
+  printf ';39m,\033[0m\033[1;34m'
+  printf '"b"\033[0m\033[1;39m:\033'
+  printf '[0m\033[0;39mfalse\033'
+  printf '[0m\033[1;39m\033[1;39'
+  printf 'm}\033[0m\033[1;39m,\033['
+  printf '0;39m123\033[0m\033[1;'
+  printf '39m,\033[0;90mnull\033'
+  printf '[0m\033[1;39m\033[1;39'
   printf 'm]\033[0m\n'
 } > $d/expect
 cmp $d/color $d/expect
@@ -517,23 +517,23 @@ if $test_no_color && command -v script >/dev/null 2>&1; then
 
   faketty $JQ_NO_B -n . > $d/color
   printf '\033[0;90mnull\033[0m\r\n' > $d/expect
-  od -c $d/expect
-  od -c $d/color
+  od -tc $d/expect
+  od -tc $d/color
   cmp $d/color $d/expect
   NO_COLOR= faketty $JQ_NO_B -n . > $d/color
   printf '\033[0;90mnull\033[0m\r\n' > $d/expect
-  od -c $d/expect
-  od -c $d/color
+  od -tc $d/expect
+  od -tc $d/color
   cmp $d/color $d/expect
   NO_COLOR=1 faketty $JQ_NO_B -n . > $d/color
   printf 'null\r\n' > $d/expect
-  od -c $d/expect
-  od -c $d/color
+  od -tc $d/expect
+  od -tc $d/color
   cmp $d/color $d/expect
   NO_COLOR=1 faketty $JQ_NO_B -Cn . > $d/color
   printf '\033[0;90mnull\033[0m\r\n' > $d/expect
-  od -c $d/expect
-  od -c $d/color
+  od -tc $d/expect
+  od -tc $d/color
   cmp $d/color $d/expect
 fi
 
@@ -566,17 +566,52 @@ if ! $VALGRIND $Q $JQ -n -f "$JQTESTDIR/yes-main-program.jq" > $d/out 2>&1; then
   exit 1
 fi
 
-if ( ! $msys && ! $mingw ) && locale -a > /dev/null; then
-  locale=$(locale -a | egrep -v '^(C|LANG|POSIX|en)' | egrep -i 'utf8|utf-8' | head -1)
-  if [ -z "$locale" ]; then
+if ! $msys && ! $mingw && locales=$(locale -a); then
+  { l=$(grep -Ev '^(C|LANG|POSIX|en)' | grep -Ei '\.utf-?8$' | head -n1) ;} \
+<<EOF
+$locales
+EOF
+  if [ -z "$l" ]; then
     echo "WARNING: Not testing localization"
   else
-    date=$(LC_ALL="$locale" date +"%a %d %b %Y at %H:%M:%S")
-    if ! LC_ALL="$locale" ./jq -nRe --arg date "$date" '$date|strptime("%a %d %b %Y at %H:%M:%S")? // false'; then
+    date=$(LC_ALL=$l date +'%a %d %b %Y at %H:%M:%S')
+    if ! LC_ALL=$l $JQ -nR --arg date "$date" '$date|strptime("%a %d %b %Y at %H:%M:%S")'; then
       echo "jq does not honor LC_ALL environment variable"
-      exit 1;
+      exit 1
     fi
   fi
 fi
+
+# Comments!
+if ! x=$($JQ -n '123 # comment') || [ "$x" != 123 ]; then
+  echo 'comment did not work'
+  exit 1
+fi
+
+cr=$(printf \\r)
+if ! x=$($JQ -n "1 # foo$cr + 2") || [ "$x" != 1 ]; then
+  echo 'regression: carriage return terminates comment'
+  exit 1
+fi
+
+# CVE-2023-50268: No stack overflow comparing a nan with a large payload
+$VALGRIND $Q $JQ '1 != .' <<\EOF >/dev/null
+Nan4000
+EOF
+
+# Allow passing the inline jq script before -- #2919
+if ! r=$($JQ --args -rn -- '$ARGS.positional[0]' bar) || [ "$r" != bar ]; then
+    echo "passing the inline script after -- didn't work"
+    exit 1
+fi
+if ! r=$($JQ --args -rn 1 -- '$ARGS.positional[0]' bar) || [ "$r" != 1 ]; then
+    echo "passing the inline script before -- didn't work"
+    exit 1
+fi
+
+# CVE-2023-50246: No heap overflow for '-10E-1000000001'
+$VALGRIND $Q $JQ . <<\NUM
+-10E-1000000001
+NUM
 
 exit 0
